[general] added cke_i to iob_soc
IObundle/iob-soc pull request #592
Opened 2023-08-25 15:07 UTC by AndreMerendeira

2023-08-25 18:57 UTC, arturum1 requested changes

2023-08-25 18:57 UTC, arturum1 commented on scripts/iob_soc_create_wrapper_files.py
> +      .rst(arst_i),
These lines are used to generate the interconnect instance in every wrapper that needs one.
Therefore, the signals generated must have a common name to all wrappers.

Currently, the `iob_soc_sim_wrapper.v` and the `iob_soc_fpga_wrapper.v` of the CYCLONEV are the only wrappers that use this interconnect, and they contain the common wires signals `clk` and `rst`.
They do NOT contain the `arst_i` signal, therefore trying to generate an interconnect with this signal will give an error (that is why those checks are failing).

I suggest keeping the common `clk` and `rst` signals.
```suggestion
      .clk(clk),
      .rst(rst),
```

Another solution would be to make sure the `clk_i` and `arst_i` signals exist in the wrappers.

2023-08-26 11:14 UTC, jjts commented
Rst cannot connect to arst

They have a different meaning

Use arst for async reset (posedge)

Use rst for sync reset (no posedge)



On Fri, Aug 25, 2023, 19:57 arturum1 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In scripts/iob_soc_create_wrapper_files.py
> <https://github.com/IObundle/iob-soc/pull/592#discussion_r1306042016>:
>
> > +      .clk(clk_i),
> +      .rst(arst_i),
>
> These lines are used to generate the interconnect instance in every
> wrapper that needs one.
> Therefore, the signals generated must have a common name to all wrappers.
>
> Currently, the iob_soc_sim_wrapper.v and the iob_soc_fpga_wrapper.v of
> the CYCLONEV are the only wrappers that use this interconnect, and they
> contain the common wires signals clk and rst.
> They do NOT contain the arst_i signal, therefore trying to generate an
> interconnect with this signal will give an error (that is why those checks
> are failing).
>
> I suggest keeping the common clk and rst signals.
> ⬇️ Suggested change
>
> -      .clk(clk_i),
> -      .rst(arst_i),
> +      .clk(clk),
> +      .rst(rst),
>
> Another solution would be to make sure the clk_i and arst_i signals exist
> in the wrappers.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IObundle/iob-soc/pull/592#pullrequestreview-1596337378>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLUHO7UCGDJQ2RVIOUZTULXXDYR7ANCNFSM6AAAAAA36UP63E>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-08-26 18:48 UTC, jjts commented
Checks fail , can't merge

2023-09-20 12:53 UTC, jjts commented
the author has no time to fix this - closing

2023-09-20 12:53 UTC, closed without merging