update memwrap
IObundle/iob-soc pull request #795
Opened 2024-02-27 16:20 UTC by Vasco-Luz

a updated version of the memwrap,

2024-02-27 16:37 UTC, AndreMerendeira requested changes

2024-02-27 16:37 UTC, AndreMerendeira commented on hardware/src/iob_soc_int_mem.v
> +   wire [SRAM_ADDR_W-3:0] ram_d_addr_ont;
Why change this name to _ont?

2024-02-27 16:37 UTC, AndreMerendeira commented on hardware/src/iob_soc_sram.v
> +   wire d_valid_ont = i_valid_o ? 1'b0 : d_valid_o;
Again, _ont

2024-02-28 15:34 UTC, AndreMerendeira approved these changes

2024-02-28 15:38 UTC, P-Miranda approved these changes

2024-02-28 15:55 UTC, arturum1 requested changes

2024-02-28 15:55 UTC, arturum1 commented on hardware/src/iob_soc.v
> +      .wdata_SPRAM_o(wdata_SPRAM_o),
```suggestion
      .wdata_spram_o(wdata_spram_o),
```

2024-02-28 15:55 UTC, arturum1 commented on hardware/src/iob_soc_sram.v
> +   output     [     DATA_W-1:0] d_rdata_i,
Why was this change made?
It seems that the new suffixes are inverted in relation to the port type (`input` type using the `_o` suffix, and vice versa)

2024-02-28 15:55 UTC, arturum1 commented on hardware/src/iob_soc_sram.v
> +   assign wstrb_spram_o = i_valid_o ? i_wstrb_o : d_wstrb_o;
Same as the previous comment. The signals on the right hand side of the expressions (like  `iob_valid_o`) are input ports

2024-02-28 16:14 UTC, Vasco-Luz commented on hardware/src/iob_soc_sram.v
> +   output     [     DATA_W-1:0] d_rdata_i,
attention mistake

2024-02-28 16:17 UTC, arturum1 approved these changes

2024-02-28 20:51 UTC, merged