Almost all hw modules converted to py2hwsw syntax
IObundle/iob-soc pull request #838
Opened 2024-05-05 18:21 UTC by Edw590

Some modules don't pass the tests because autogenerated files are missing but the big majority passes.

Modules iob_split, uart and merge were not converted because of being more complex.

2024-05-05 18:39 UTC, jjts commented
Why do they need auto-generated files? They have their verilog.

2024-05-05 19:53 UTC, Edw590 commented
The Verilog files include .vs files. Some of those are not being generated

2024-05-06 19:54 UTC, arturum1 requested changes

2024-05-06 19:54 UTC, arturum1 commented on lib/hardware/modules/div/iob_div_subshift/iob_div_subshift.py
> +                "name": "clk_en_rst",
```suggestion
                "name": "clk_en_rst",
                "type": "slave",
```
This port is missing the `type` key.
Without this key, the scripts assume the interface is of type 'master' and are therefore generating ports in the wrong direction.

2024-05-06 19:54 UTC, arturum1 commented on lib/hardware/modules/div/iob_div_subshift/iob_div_subshift.py
> +                "name": "clk_en_rst",
The `type` key also seems to be missing from the `clk_en_rst` port of other modules in this PR.

2024-05-06 19:59 UTC, arturum1 commented on lib/hardware/modules/iob_timer/iob_timer.py
To check if the scripts are generating the core correctly, I'm running this command to setup:
`py2hwsw.py iob_timer setup --no_verilog_lint`
Followed by this command to run with Icarus Verilog:
`make -C ../iob_timer_V0.1/ sim-run`

2024-05-08 05:28 UTC, arturum1 commented on lib/hardware/modules/div/iob_div_subshift/iob_div_subshift.py
> +                "name": "clk_en_rst",
Resolved in https://github.com/IObundle/iob-soc/pull/840

2024-05-08 05:29 UTC, arturum1 approved these changes
New fixes in PR https://github.com/IObundle/iob-soc/pull/840

2024-05-08 06:25 UTC, merged