Remove macros from some modules
IObundle/iob-soc pull request #880
Opened 2024-07-31 21:22 UTC by Edw590

2024-07-31 23:35 UTC, arturum1 requested changes
Besides some missing `iob_function` includes, changes look good.

2024-07-31 23:35 UTC, arturum1 commented on lib/hardware/modules/fifo/iob_fifo_async/hardware/src/iob_fifo_async.v
```suggestion

`include "iob_functions.vs"
```

2024-07-31 23:35 UTC, arturum1 commented on lib/hardware/modules/fifo/iob_fifo_async/iob_fifo_async.py
> +            },
```suggestion
            },
            {
                "core_name": "iob_functions",
                "instance_name": "iob_functions_inst",
            },
```

2024-07-31 23:35 UTC, arturum1 commented on lib/hardware/modules/fifo/iob_fifo_async/hardware/simulation/src/iob_fifo_async_tb.v
```suggestion

`include "iob_functions.vs"
```

2024-07-31 23:35 UTC, arturum1 commented on lib/hardware/modules/fifo/iob_fifo_sync/hardware/src/iob_fifo_sync.v
```suggestion

`include "iob_functions.vs"
```

2024-07-31 23:35 UTC, arturum1 commented on lib/hardware/modules/fifo/iob_fifo_sync/hardware/simulation/src/iob_fifo_sync_tb.v
```suggestion

`include "iob_functions.vs"
```

2024-07-31 23:35 UTC, arturum1 commented on lib/hardware/modules/fifo/iob_fifo_sync/hardware/src/iob_fifo_sync.v
We should also include the `iob_functions` module in the [iob_fifo_sync.py `blocks` list](https://github.com/Edw590/iob-soc/blob/if_gen2/lib/hardware/modules/fifo/iob_fifo_sync/iob_fifo_sync.py#L153).

2024-07-31 23:39 UTC, arturum1 commented
I'm looking back at the commits, and noticing that the `iob_functions` include was removed from some modules.
Example: https://github.com/IObundle/iob-soc/pull/880/commits/3877fd6dc3fc2b67d9d8164370627d148b752dca

Is this because we can't include `iob_functions` in multiple modules if they are used in the same project (due to duplicate includes)?

2024-07-31 23:43 UTC, arturum1 commented
> I'm looking back at the commits, and noticing that the `iob_functions` include was removed from some modules. Example: [3877fd6](https://github.com/IObundle/iob-soc/commit/3877fd6dc3fc2b67d9d8164370627d148b752dca)
> 
> Is this because we can't include `iob_functions` in multiple modules if they are used in the same project (due to duplicate includes)?

If this is the issue that causes some modules to not have the `iob_functions` include, then maybe we could fix it by including the functions inside the verilog module, instead of the top of the file?

Including inside the verilog module should prevent the functions from being project-wide and conflicting with functions in other modules.

2024-08-01 11:09 UTC, jjts commented
Functions must be defined in modules and are only known therein.

On Thu, Aug 1, 2024, 00:43 arturum1 ***@***.***> wrote:

> I'm looking back at the commits, and noticing that the iob_functions
> include was removed from some modules. Example: 3877fd6
> <https://github.com/IObundle/iob-soc/commit/3877fd6dc3fc2b67d9d8164370627d148b752dca>
>
> Is this because we can't include iob_functions in multiple modules if
> they are used in the same project (due to duplicate includes)?
>
> If this is the issue that causes some modules to not have the
> iob_functions include, then maybe we could fix it by including the
> functions inside the verilog module, instead of the top of the file?
>
> Including inside the verilog module should prevent the functions from
> being project-wide and conflicting with functions in other modules.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IObundle/iob-soc/pull/880#issuecomment-2261666647>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLUHO2PJYKAGLDCMBDUBRLZPFZDFAVCNFSM6AAAAABLZIZLWKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENRRGY3DMNRUG4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-08-01 14:56 UTC, Edw590 commented
Good idea. Didn't come to my mind. It's done!

2024-08-01 18:55 UTC, arturum1 approved these changes

2024-08-01 22:00 UTC, merged