Create iob_rom_2p
IObundle/iob-soc pull request #938
Opened 2024-08-30 13:30 UTC by Edw590

2024-08-30 17:01 UTC, arturum1 requested changes

2024-08-30 17:01 UTC, arturum1 commented on lib/hardware/memories/rom/iob_rom_2p/hardware/src/iob_rom_2p.v
> +   output [DATA_W-1:0] r_data_o
If two masters request to read at the same time (at different addresses), how does each of them know if the `r_data_o` is valid for their request?
We should probably add a `ready` or `rvalid` signal for each port to convey this information.

2024-08-30 17:32 UTC, jjts commented
this is done for ram2p
Com os melhores cumprimentos / Best regards,

Jose T. de Sousa


On Fri, Aug 30, 2024 at 6:01 PM arturum1 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In lib/hardware/memories/rom/iob_rom_2p/hardware/src/iob_rom_2p.v
> <https://github.com/IObundle/iob-soc/pull/938#discussion_r1739138499>:
>
> > +   //read port 1
> +   input               r1_en_i,
> +   input  [ADDR_W-1:0] r1_addr_i,
> +
> +   //read port 2
> +   input               r2_en_i,
> +   input  [ADDR_W-1:0] r2_addr_i,
> +
> +   output [DATA_W-1:0] r_data_o
>
> If two masters request to read at the same time (at different addresses),
> how does each of them know if the r_data_o is valid for their request?
> We should probably add a ready or rvalid signal for each port to convey
> this information.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IObundle/iob-soc/pull/938#pullrequestreview-2273082503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLUHO5IXHASCW4FARAWHOTZUCQQDAVCNFSM6AAAAABNMP2ULCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENZTGA4DENJQGM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-08-31 13:24 UTC, Edw590 commented
I began by adding the ready signals, but after programming it I realized they were basically equal to the enable signals. So I thought in removing it and letting the programmer know that if 2 masters request the ROM, only the first one will get the data until the enable is put down. But I can add them again.

2024-09-02 14:41 UTC, arturum1 approved these changes

2024-09-02 17:22 UTC, arturum1 requested changes

2024-09-02 17:22 UTC, arturum1 commented on lib/hardware/memories/rom/iob_rom_2p/hardware/src/iob_rom_2p.v
> +   assign r2_ready_o = r1_en_i ? 0 : r2_en_i;
```suggestion
   assign r1_ready_o = 1'b1;
   assign r2_ready_o = ~r1_en_i;
```

2024-09-09 16:08 UTC, closed without merging